version: '3.8'

services:
  streamlit:
    build:
      context: ./frontend
    container_name: streamlit
    ports:
      - "8501:8501"
    networks:
      - my-bridge

  api:
    build:
      context: ./backend
    container_name: api
    ports:
      - "8000:8000"
    networks:
      - my-bridge

networks:
  my-bridge:
    driver: bridge