version: '3.8'

services:
  streamlit:
    build:
      context: ./frontend
    container_name: streamlit
    ports:
      - "8501:8501"
    networks:
      - my-bridge
    volumes:
      - ./frontend/logs/:/usr/src/app/logs/

  api:
    build:
      context: ./backend
    container_name: api
    ports:
      - "8000:8000"
    networks:
      - my-bridge
    volumes:
      - ./backend/logs/:/usr/src/app/logs/


networks:
  my-bridge:
    driver: bridge